name: leafletjs
version: 0.0.1
description: Leaflet.js wrapper for Dart
author: Renat Valeev <renat.valeev@gmail.com>
homepage: https://github.com/rvaleev/leafletjs.dart
environment:
  sdk: '>=1.13.1 <2.0.0'
dependencies:
  js: ^0.6.1
  func: ^0.1.0
dev_dependencies:
  browser: ^0.10.0+2
  parsejs: ^1.1.0
